name: Theme Check
on: [push, pull_request]

permissions:
  contents: read       # нужно читать файлы
  checks: write        # нужно создавать и обновлять Check-run

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Theme Check
        uses: shopify/theme-check-action@v2
        with:
          token: ${{ github.token }}   # позволяет Action публиковать результаты как аннотации
          base: main                   # опционально, для diff-аннотаций по сравнению с main
